version: '3.4'

services:
  bodyshedule:
    image: ${DOCKER_REGISTRY-}bodyshedule
    build:
      context: .
      dockerfile: bodyshedule/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=postgresql;Username=postgres;Port=5432;Password=Admin666!;Database=MyBody;Pooling=true;
    ports:
      - "80:80"
  